TecTools: template/tectools/layout/activity-center.php File Reference
activity-center.php File Reference
Variables
$TecTools = $GLOBALS['TecTools']
$logTypes = $this->RCMS->Logs->getLogTypes()
$logs = $this->RCMS->Logs->getLogs()
$pages = ceil(count($logs) / 10)
foreach($logTypes as $logType)(this)" data-log-type-id endforeach ="<?= $logType['LogTypeID'] ?>" class="log-type"><?= "{$logType['LogTypeName']} ({$logType['count']}x)"
Variable Documentation
$logs
$logs = $this->RCMS->Logs->getLogs()
Definition at line 15 of file activity-center.php.
Referenced by Logs\getLogs().
$logTypes
$logTypes = $this->RCMS->Logs->getLogTypes()
Definition at line 14 of file activity-center.php.
$pages
$pages = ceil(count($logs) / 10)
Definition at line 17 of file activity-center.php.
Referenced by RCMSTables\buildRows(), and TecTools\displayFrontPagePagination().
$TecTools
ifTecTools $TecTools = $GLOBALS['TecTools']
Definition at line 12 of file activity-center.php.
endforeach
foreach ($logs as $log) ('d. %e %B kl. %H:%M:%S', strtotime($log['Created'])) ?></td> <td><? endforeach ="<?= $logType['LogTypeID'] ?>" class="log-type"><?= "{$logType['LogTypeName']} ({$logType['count']}x)"
Definition at line 31 of file activity-center.php.