TecTools: docs/andet.txt File Reference
docs/andet.txt File Reference
Data Structures
class TecToolsCategories
class Base
Functions
columns forEach (col=> { let cards=col.element.parentElement.parentElement.parentElement.parentElement.querySelectorAll('div.mr-4');cards.forEach(card=> { let body=card.querySelector('.js-comment-body').innerText;let addedBy=card.querySelector('small.text-gray-light').innerText;let c={ 'body':body, 'addedBy':addedBy};col.cards.push(c);});})
columns forEach (col=> { delete col.element;})
JSON stringify (columns)<?php override class Base
initCustomColors ()
customBackgroundColorChange (event)
customTextColorChange (event)
Variables
Få alle tools og kategorier som værktøjet har SELECT *FROM Tools p1 LEFT JOIN Manufacturers p2 ON p1 FK_ManufacturerID
Få alle tools og kategorier som værktøjet har SELECT *FROM Tools p1 LEFT JOIN Manufacturers p2 ON p1 N til pagination Slet gamle billeder efter upload custom form location account creation errors rediger bruger abonnement siden
Få alle tools og kategorier som værktøjet har SELECT *FROM Tools p1 LEFT JOIN Manufacturers p2 ON p1 N til pagination Slet gamle billeder efter upload custom form location account creation errors rediger bruger abonnement gør pænere slet værktøj form validation js skriv på siden når en reservation er overskredet notifikationer på hjemmesiden notifikationer via email UX test bruger gruppe som skal teste sidens anvendelighed let columns = []
Function Documentation
customBackgroundColorChange()
customBackgroundColorChange (event)
Definition at line 331 of file andet.txt.
Referenced by initCustomColors().
customTextColorChange()
customTextColorChange (event)
Definition at line 339 of file andet.txt.
Referenced by initCustomColors().
forEach() [1/2]
columns forEach (col , { delete col.element;})
forEach() [2/2]
columns forEach (col , { let cards=col.element.parentElement.parentElement.parentElement.parentElement.querySelectorAll('div.mr-4');cards.forEach(card=> { let body=card.querySelector('.js-comment-body').innerText;let addedBy=card.querySelector('small.text-gray-light').innerText;let c={ 'body':body, 'addedBy':addedBy};col.cards.push(c);});})
initCustomColors()
initCustomColors ()
Definition at line 302 of file andet.txt.
References customBackgroundColorChange(), and customTextColorChange().
stringify()
JSON stringify (columns) pure virtual
Definition at line 56 of file andet.txt.
References Base::$allowedEndpoints, Base::__construct(), and Base::handlePOSTEndpoints().
Variable Documentation
columns
Få alle tools og kategorier som værktøjet har SELECT* FROM Tools p1 LEFT JOIN Manufacturers p2 ON p1 N til pagination Slet gamle billeder efter upload custom form location account creation errors rediger bruger abonnement gør pænere slet værktøj form validation js skriv på siden når en reservation er overskredet notifikationer på hjemmesiden notifikationer via email UX test bruger gruppe som skal teste sidens anvendelighed let columns = []
Definition at line 35 of file andet.txt.
Referenced by RCMSTables::buildRows(), RCMSTables::createHTML(), RCMSTables::createRCMSTable(), and RCMSTables::loadAjax().
FK_ManufacturerID
Få alle tools og kategorier som værktøjet har SELECT* FROM Tools p1 LEFT JOIN Manufacturers p2 ON p1 FK_ManufacturerID
Initial value:
= p2.ManufacturerID
LEFT JOIN
Categories p3 ON p3.CategoryID IN (SELECT FK_CategoryID FROM CategoryTools WHERE FK_ToolID = p1.ToolID)
Få alle kategorier med deres navne
SELECT * FROM Categories WHERE CategoryID IN (SELECT FK_CategoryID FROM CategoryTools WHERE FK_ToolID = 2)
Brug IF statements i Stored Procedures når vi skal filtrere på søgeord og kategorier
Mulighed for at vælge mere end 1 kategori
Brug LIMIT N
Definition at line 4 of file andet.txt.
siden
Få alle tools og kategorier som værktøjet har SELECT* FROM Tools p1 LEFT JOIN Manufacturers p2 ON p1 N til pagination Slet gamle billeder efter upload custom form location account creation errors rediger bruger abonnement siden
Definition at line 23 of file andet.txt.
Referenced by TecTools::contactCustomerService().