TecTools: Mailer Class Reference
Mailer Class Reference
Public Member Functions
__construct (RCMS $RCMS)
Static Public Member Functions
static sendEmail (string $fromEmail, string $fromName, string $recepientEmail, string $recepientName, string $subject, string $body, array $physicalFiles=[], array $dynamicPDFFiles=[], string $logoID='', string $logoPath='')
Data Fields
RCMS $RCMS
Static Public Attributes
static bool $disableAutoLoading
Detailed Description
Class Mailer Denne klasse fungerer som en wrapper til SwiftMailer. Den indeholder en metode, som gør det nemmere at sende mails og reducere mængden af kode der skal skrives.
Definition at line 10 of file Mailer.php.
Constructor & Destructor Documentation
__construct()
__construct (RCMS $RCMS)
Definition at line 23 of file Mailer.php.
References $RCMS.
Member Function Documentation
sendEmail()
static sendEmail (string $fromEmail, string $fromName, string $recepientEmail, string $recepientName, string $subject, string $body, array $physicalFiles = [], array $dynamicPDFFiles = [], string $logoID = '', string $logoPath = '') static
Sender en email. Benytter konfiguration sat i config.php Benytter SwiftMailer til at sende mailen.
Parameters
string $fromEmail Afsender e-mail adresse
string $fromName Afsender navn
string $recepientEmail Modtager e-mail adresse
string $recepientName Modtager navn
string $subject Mailemne
string $body Mailbrødtekst, mulighed for HTML
array $physicalFiles Array af fysiske filer der eksisterer på filsystemet som vedhæftes
array $dynamicPDFFiles Array med arrays af data som laves om til PDF filer og vedhæftes
string $logoID ID'et på logoet, til brug i brødteksten
string $logoPath Stien til logoet der skal bruges i mailen
Returns
bool
Definition at line 43 of file Mailer.php.
Referenced by TecTools\contactCustomerService(), CheckIns\sendFinePaidEmail(), Cronjobs\sendMailOldReservationDeleted(), CheckIns\sendNewCheckInEmail(), CheckIns\sendNewFineEmail(), and Login\sendResetPasswordMail().
Field Documentation
$disableAutoLoading
bool $disableAutoLoading static
Forhindrer RCMS at loade denne klasse automatisk
Definition at line 20 of file Mailer.php.
$RCMS
RCMS $RCMS
Definition at line 14 of file Mailer.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
include/Mailer.php