TecTools: Login Class Reference
Login Class Reference
Public Member Functions
__construct (RCMS $RCMS)
isLoggedIn ()
getUserByEmail (string $email)
log_in ()
createUser ()
isAdmin ()
getEmail ()
getFirstName ()
getLastName ()
getUserID ()
getUserLevel ()
log_out (string $customLocation='')
hashPass (string $pass)
Data Fields
RCMS $RCMS
const STANDARD_USER_LEVEL = 1
const MIN_LEVEL_FOR_ADMIN = 9
Private Member Functions
resetPassword ()
sendResetPasswordMail (string $fullName, string $url, string $emailAddress)
resetPasswordVerify ()
getPasswordReset (string $hash)
setLoginCookies ()
addUserToStripe (string $firstname, string $lastname, string $email, string $phone, string $address, string $zipcode, string $city)
Detailed Description
Class Login Denne klasse indeholder metoder der vedrører brugere i RCMS generelt Indeholder bl.a. metoder til at oprette bruger, logge ind og logge ud
Definition at line 12 of file Login.php.
Constructor & Destructor Documentation
__construct()
__construct (RCMS $RCMS)
Definition at line 21 of file Login.php.
References $_GET, $RCMS, createUser(), log_in(), log_out(), resetPassword(), resetPasswordVerify(), and setLoginCookies().
Member Function Documentation
addUserToStripe()
addUserToStripe (string $firstname, string $lastname, string $email, string $phone, string $address, string $zipcode, string $city) private
Tilføjer en bruger som en customer i Stripe og returnerer det customer ID som Stripe returnerer efter oprettelse
Parameters
string $firstname
string $lastname
string $email
string $phone
string $address
string $zipcode
string $city
Returns
string
Exceptions
ApiErrorException
Definition at line 278 of file Login.php.
Referenced by createUser().
createUser()
createUser ()
Opretter en bruger via en POST request
Returns
void
Exceptions
ApiErrorException @noinspection PhpUndefinedVariableInspection
Definition at line 231 of file Login.php.
References $_SESSION, $userID, addUserToStripe(), Logs\CREATE_USER_TYPE_ID, RCMS\execute(), hashPass(), log_in(), and Helpers\redirect().
Referenced by __construct().
getEmail()
getEmail ()
Returnerer brugerens email
Returns
bool|string
Definition at line 317 of file Login.php.
References $_SESSION.
getFirstName()
getFirstName ()
Returnerer brugerens fornavn
Returns
bool|string
Definition at line 325 of file Login.php.
References $_SESSION.
getLastName()
getLastName ()
Returnerer brugerens efternavn
Returns
bool|string
Definition at line 333 of file Login.php.
References $_SESSION.
getPasswordReset()
getPasswordReset (string $hash) private
Returnerer en adgangskode gendannelse fra databasen, hvis den eksisterer
Parameters
string $hash
Returns
array|false
Definition at line 163 of file Login.php.
References RCMS\execute().
Referenced by resetPasswordVerify().
getUserByEmail()
getUserByEmail (string $email)
Henter en bruger ud af databasen via deres email
Parameters
string $email
Returns
array|false|null
Definition at line 188 of file Login.php.
References RCMS\execute().
Referenced by log_in(), and resetPassword().
getUserID()
getUserID ()
Returnerer brugerens ID
Returns
bool|int
Definition at line 341 of file Login.php.
References $_SESSION.
Referenced by log_out().
getUserLevel()
getUserLevel ()
Returnerer 1 hvis brugeren er standard, eller 9 hvis brugeren er personale
Returns
bool|int
Definition at line 349 of file Login.php.
References $_SESSION.
Referenced by isAdmin().
hashPass()
hashPass (string $pass)
Hasher og salter brugerens adgangskode
Parameters
string $pass Brugerens adgangskode
Returns
string
Definition at line 374 of file Login.php.
Referenced by createUser(), and resetPasswordVerify().
isAdmin()
isAdmin ()
Returnerer true hvis brugeren er personale, ellers false
Returns
bool
Definition at line 309 of file Login.php.
References getUserLevel().
Referenced by setLoginCookies().
isLoggedIn()
isLoggedIn ()
Returnerer true hvis brugeren er logget ind, ellers false
Returns
bool
Definition at line 179 of file Login.php.
References $_SESSION.
log_in()
log_in ()
Logger en bruger ind via en POST request
Returns
void
Exceptions
JsonException
Definition at line 197 of file Login.php.
References $_SESSION, $user, getUserByEmail(), Logs\LOG_IN_TYPE_ID, Helpers\redirect(), and Helpers\setNotification().
Referenced by __construct(), and createUser().
log_out()
log_out (string $customLocation = '')
Logger en bruger ud fra siden ved at slette brugeren fra $_SESSION
Parameters
string $customLocation URL som brugeren skal sendes til efter man er blevet logget ud
Returns
void
Definition at line 358 of file Login.php.
References $_SESSION, getUserID(), and Logs\LOG_OUT_TYPE_ID.
Referenced by __construct().
resetPassword()
resetPassword () private
Begynder processen til at gendanne et password Opretter et hash i databasen og sender en mail til den person som gerne vil gendanne sit password Via POST request
Exceptions
JsonException
Definition at line 53 of file Login.php.
References $user, RCMS\execute(), Helpers\getHTTPHost(), getUserByEmail(), Helpers\guidv4(), Helpers\redirect(), sendResetPasswordMail(), and Helpers\setNotification().
Referenced by __construct().
resetPasswordVerify()
resetPasswordVerify () private
Denne metode validere en adgangskode gendannelse Tjekker at linket ikke er brugt og at der ikke er gået 30 minutter, siden linket blev genereret Via POST request
Exceptions
JsonException
Definition at line 111 of file Login.php.
References RCMS\execute(), getPasswordReset(), hashPass(), Helpers\redirect(), and Helpers\setNotification().
Referenced by __construct().
sendResetPasswordMail()
sendResetPasswordMail (string $fullName, string $url, string $emailAddress) private
Sender en mail som indeholder et link hvor brugeren kan vælge en ny adgangskode
Parameters
string $fullName
string $url
string $emailAddress
Definition at line 79 of file Login.php.
References RCMS\getTemplateFolder(), and Mailer\sendEmail().
Referenced by resetPassword().
setLoginCookies()
setLoginCookies () private
Sætter nogle cookies relateret til RCMS som skal bruges på frontend
Definition at line 170 of file Login.php.
References isAdmin().
Referenced by __construct().
Field Documentation
$RCMS
RCMS $RCMS
Definition at line 16 of file Login.php.
Referenced by __construct().
MIN_LEVEL_FOR_ADMIN
const MIN_LEVEL_FOR_ADMIN = 9
Definition at line 19 of file Login.php.
STANDARD_USER_LEVEL
const STANDARD_USER_LEVEL = 1
Definition at line 18 of file Login.php.
The documentation for this class was generated from the following file:
include/Login.php