TecTools: Cron Class Reference
Cron Class Reference
Public Member Functions
__construct (RCMS $RCMS)
runCronJobs ()
addCronJob (array $cronjob)
Data Fields
RCMS $RCMS
Private Member Functions
is_time_cron (int $time, string $cron)
Private Attributes
array $cronjobs
Detailed Description
Class Cron Denne klasse står for at håndtere og køre cronjobs.
For at klassen fungere, skal der manuelt tilføjes et job til crontab'en på Linux serveren, som skal køre denne fil. Denne fil skal køres ligeså ofte, som det job man tilføjer med denne klasse der køres oftest.
Forklaring: Hvis man gerne vil tilføje et job med denne klasse, som skal køres hvert 5. minut, så skal jobbet man manuelt har tilføjet til crontab'en køre denne fil minimum ligeså ofte. Man må gerne køre denne fil endnu oftere, som f.eks. hvert minut, det må bare ikke være mindre hyppigt.
Til TecTools projektet køre vi denne fil hvert minut, hvilket betyder at denne klasse tjekker 5 gange i minuttet om vores job til at slette reservationer skal køres. Vores job til at slette reservationer bliver stadig kun kørt 1 gang hvert 5. minut.
Definition at line 22 of file Cron.php.
Constructor & Destructor Documentation
__construct()
__construct (RCMS $RCMS)
Definition at line 30 of file Cron.php.
References $RCMS.
Member Function Documentation
addCronJob()
addCronJob (array $cronjob)
Tilføjer et cronjob
Parameters
array $cronjob
Definition at line 53 of file Cron.php.
is_time_cron()
is_time_cron (int $time, string $cron) private
Tjekker om et tidsstempel matcher et cron format F.eks. $cron = '5 0 * * *'; Reference: https://www.binarytides.com/php-check-if-a-timestamp-matches-a-given-cron-schedule/
Parameters
$time
$cron
Returns
bool
Definition at line 65 of file Cron.php.
Referenced by runCronJobs().
runCronJobs()
runCronJobs ()
Tjekker for hvert cronjob om det skal køres nu, og køre jobbet hvis det skal
Definition at line 38 of file Cron.php.
References is_time_cron().
Referenced by RCMS\__construct().
Field Documentation
$cronjobs
array $cronjobs private
Definition at line 28 of file Cron.php.
$RCMS
RCMS $RCMS
Definition at line 26 of file Cron.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
include/Cron.php