TecTools: Manufacturers Class Reference
Manufacturers Class Reference
Public Member Functions
__construct (TecTools $TecTools)
addManufacturer ()
deleteManufacturer ()
getManufacturer (int $manufacturerID)
editManufacturer ()
getAllManufacturers ()
Data Fields
RCMS $RCMS
TecTools $TecTools
Static Public Attributes
static bool $disableAutoLoading
static array $allowedEndpoints
Private Member Functions
isManufacturerInUse (int $manufacturerID)
manufacturerExists (string $name)
Detailed Description
Class Manufacturers Denne klasse indeholder metoder som vedrører producenter på TecTools siden Den indeholder metoder til bl.a. oprette, redigere og hente producenter
Definition at line 10 of file Manufacturers.php.
Constructor & Destructor Documentation
__construct()
__construct (TecTools $TecTools)
Definition at line 36 of file Manufacturers.php.
References $TecTools.
Member Function Documentation
addManufacturer()
addManufacturer ()
Tilføjer en producent via en POST request
Returns
void
Definition at line 47 of file Manufacturers.php.
References Logs\CREATE_MANUFACTURER_TYPE_ID, RCMS\execute(), manufacturerExists(), Helpers\redirect(), and Helpers\setNotification().
deleteManufacturer()
deleteManufacturer ()
Sletter en producent via POST request
Definition at line 71 of file Manufacturers.php.
References RCMS\execute(), isManufacturerInUse(), and Helpers\setNotification().
editManufacturer()
editManufacturer ()
Redigerer en producent via en POST request
Returns
void
Definition at line 117 of file Manufacturers.php.
References Logs\EDIT_MANUFACTURER_TYPE_ID, RCMS\execute(), manufacturerExists(), Helpers\redirect(), and Helpers\setNotification().
getAllManufacturers()
getAllManufacturers ()
Henter alle producenter ud fra databasen
Returns
array
Definition at line 143 of file Manufacturers.php.
References RCMS\execute().
getManufacturer()
getManufacturer (int $manufacturerID)
Returnerer en producent
Parameters
int $manufacturerID
Returns
array|null
Definition at line 108 of file Manufacturers.php.
References RCMS\execute().
isManufacturerInUse()
isManufacturerInUse (int $manufacturerID) private
Tjekker om en producent bliver benyttet på nuværende tidspunkt
Parameters
int $manufacturerID
Returns
bool
Definition at line 88 of file Manufacturers.php.
References RCMS\execute().
Referenced by deleteManufacturer().
manufacturerExists()
manufacturerExists (string $name) private
Tjekker om en producent med samme navn allerede eksisterer i databasen
Parameters
$name
Returns
bool
Definition at line 98 of file Manufacturers.php.
References RCMS\execute().
Referenced by addManufacturer(), and editManufacturer().
Field Documentation
$allowedEndpoints
array $allowedEndpoints static
Initial value:
= [
        'addManufacturer', 'editManufacturer', 'deleteManufacturer'
    ]
Definition at line 27 of file Manufacturers.php.
$disableAutoLoading
bool $disableAutoLoading static
Forhindrer RCMS at loade denne klasse automatisk
Definition at line 20 of file Manufacturers.php.
$RCMS
RCMS $RCMS
Definition at line 14 of file Manufacturers.php.
$TecTools
TecTools $TecTools
Definition at line 34 of file Manufacturers.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
include/plugins/TecTools/Manufacturers.php