TecTools: Base Class Reference
Base Class Reference
Public Member Functions
__construct ()
handlePOSTEndpoints ()
Static Public Attributes
static array $allowedEndpoints = []
Detailed Description
Class Base Denne klasse er fundamentet for alle vores andre klasser, som indeholder metoder der skal køres ved POST requests. Klassen eksister kun for at reducere duplikeret kode, ved at give alle underklasser adgang til variablen $allowedEndpoints og metoden handlePOSTEndpoints. Den kan selvfølgelig udvides senere, hvis der er andre metoder man gerne vil have adgang til at alle underklasser.
Definition at line 222 of file andet.txt.
Member Function Documentation
__construct()
__construct ()
Definition at line 230 of file andet.txt.
References handlePOSTEndpoints().
Referenced by stringify().
handlePOSTEndpoints()
handlePOSTEndpoints ()
Denne metode tjekker, om $_POST arrayet indeholder navnet på en metode i denne klasse (og underklasse), tjekker derefter om det er en af de tilladte endpoints, og eksekvere efterfølgende metoden hvis det er tilfældet
Det er endda muligt for handlePOSTEndpoints at overdrage funktionsparametre til målfunktionen
Definition at line 241 of file andet.txt.
References Helpers::setNotification().
Referenced by __construct(), and stringify().
Field Documentation
$allowedEndpoints
array $allowedEndpoints = [] static
Definition at line 228 of file andet.txt.
Referenced by stringify().
The documentation for this class was generated from the following file:
docs/andet.txt