TecTools: Categories Class Reference
Categories Class Reference
Public Member Functions
__construct (TecTools $TecTools)
getCategory (int $categoryID)
removeAllCategoriesFromTool (int $toolID)
addToolToCategory (int $toolID, int $categoryID)
getCategoriesForTool (int $toolID)
getAllCategories ()
Public Member Functions inherited from Base
__construct ()
handlePOSTEndpoints ()
Data Fields
RCMS $RCMS
TecTools $TecTools
Static Public Attributes
static bool $disableAutoLoading
static array $allowedEndpoints
Static Public Attributes inherited from Base
static array $allowedEndpoints = []
Protected Member Functions
addCategory ()
editCategory ()
Private Member Functions
categoryExists ($name)
Detailed Description
Class Categories Denne klasse indeholder metoder som vedrører kategorier på TecTools siden Den indeholder metoder til bl.a. oprette, redigere og hente kategorier
Definition at line 10 of file Categories.php.
Constructor & Destructor Documentation
__construct()
__construct (TecTools $TecTools)
Definition at line 31 of file Categories.php.
References $TecTools.
Member Function Documentation
addCategory()
addCategory () protected
Tilføjer en kategori via en POST request
Returns
void
Definition at line 42 of file Categories.php.
References categoryExists(), Logs\CREATE_CATEGORY_TYPE_ID, RCMS\execute(), Helpers\redirect(), and Helpers\setNotification().
addToolToCategory()
addToolToCategory (int $toolID, int $categoryID)
Tilføjer et værktøj til en kategori
Parameters
int $toolID
int $categoryID
Returns
void
Definition at line 128 of file Categories.php.
References RCMS\execute().
Referenced by TecTools\addTool(), and TecTools\editTool().
categoryExists()
categoryExists ($name) private
Tjekker om en kategori med samme navn allerede eksisterer i databasen
Parameters
$name
Returns
bool
Definition at line 68 of file Categories.php.
References RCMS\execute().
Referenced by addCategory(), and editCategory().
editCategory()
editCategory () protected
Redigerer en kategori via en POST request
Returns
void
Definition at line 87 of file Categories.php.
References categoryExists(), Logs\EDIT_CATEGORY_TYPE_ID, RCMS\execute(), Helpers\redirect(), and Helpers\setNotification().
getAllCategories()
getAllCategories ()
Henter alle kategorier ud fra databasen
Returns
array
Definition at line 147 of file Categories.php.
References RCMS\execute().
getCategoriesForTool()
getCategoriesForTool (int $toolID)
Henter alle kategorier ud for et værktøj fra databasen
Parameters
int $toolID
Returns
array
Definition at line 137 of file Categories.php.
References RCMS\execute().
Referenced by TecTools\getAllTools(), TecTools\getAllToolsWithFilters(), and TecTools\getToolByID().
getCategory()
getCategory (int $categoryID)
Henter en kategori ud fra databasen
Parameters
int $categoryID
Returns
array|null
Definition at line 78 of file Categories.php.
References RCMS\execute().
removeAllCategoriesFromTool()
removeAllCategoriesFromTool (int $toolID)
Fjerner alle kategorier fra et værktøj
Parameters
int $toolID
Returns
void
Definition at line 114 of file Categories.php.
References RCMS\execute().
Referenced by TecTools\editTool().
Field Documentation
$allowedEndpoints
array $allowedEndpoints static
Initial value:
= [
        'addCategory', 'editCategory'
    ]
Definition at line 22 of file Categories.php.
$disableAutoLoading
bool $disableAutoLoading static
Forhindrer RCMS at loade denne klasse automatisk
Definition at line 20 of file Categories.php.
$RCMS
RCMS $RCMS
Definition at line 14 of file Categories.php.
$TecTools
TecTools $TecTools
Definition at line 29 of file Categories.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
include/plugins/TecTools/Categories.php