TecTools: TecToolsCategories Class Reference
TecToolsCategories Class Reference
Public Member Functions
__construct (RCMS $RCMS)
getCategory (int $categoryID)
removeAllCategoriesFromTool (int $toolID)
Public Member Functions inherited from Base
__construct ()
handlePOSTEndpoints ()
Data Fields
RCMS $RCMS
Static Public Attributes
static array $allowedEndpoints
Static Public Attributes inherited from Base
static array $allowedEndpoints = []
Protected Member Functions
addCategory ()
editCategory ()
Private Member Functions
categoryExists ($name)
Detailed Description
Definition at line 94 of file andet.txt.
Member Function Documentation
__construct()
__construct (RCMS $RCMS)
Definition at line 104 of file andet.txt.
References $RCMS.
addCategory()
addCategory () protected
Tilføjer en kategori via en POST request
Returns
void
Definition at line 114 of file andet.txt.
References categoryExists(), Logs::CREATE_CATEGORY_TYPE_ID, RCMS::execute(), Helpers::redirect(), and Helpers::setNotification().
categoryExists()
categoryExists ($name) private
Tjekker om en kategori med samme navn allerede eksisterer i databasen
Parameters
$name
Returns
bool
Definition at line 140 of file andet.txt.
References RCMS::execute().
Referenced by addCategory(), and editCategory().
editCategory()
editCategory () protected
Redigerer en kategori via en POST request
Returns
void
Definition at line 159 of file andet.txt.
References categoryExists(), Logs::EDIT_CATEGORY_TYPE_ID, RCMS::execute(), Helpers::redirect(), and Helpers::setNotification().
getCategory()
getCategory (int $categoryID)
Henter en kategori ud fra databasen
Parameters
int $categoryID
Returns
array|null
Definition at line 150 of file andet.txt.
References RCMS::execute().
removeAllCategoriesFromTool()
removeAllCategoriesFromTool (int $toolID)
Fjerner alle kategorier fra et værktøj
Parameters
int $toolID
Returns
void
Definition at line 186 of file andet.txt.
References RCMS::execute().
Field Documentation
$allowedEndpoints
array $allowedEndpoints static
Initial value:
= [
        'addCategory', 'editCategory'
    ]
Definition at line 100 of file andet.txt.
$RCMS
RCMS $RCMS
Definition at line 98 of file andet.txt.
Referenced by __construct().
The documentation for this class was generated from the following file:
docs/andet.txt