TecTools: Reservations Class Reference
Reservations Class Reference
Public Member Functions
__construct (TecTools $TecTools)
isToolReserved (int $toolID, int $userID)
getReservationCountForUser (int $userID)
hasUserReachedMaxReservations (int $userID=0)
deleteReservation ()
addReservation ()
Data Fields
RCMS $RCMS
TecTools $TecTools
Static Public Attributes
static bool $disableAutoLoading
static array $allowedEndpoints
Private Member Functions
userOwnsReservation (int $reservationID)
Detailed Description
Class Reservations Denne klasse indeholder metoder som vedrører reservationer på TecTools siden Den indeholder metoder til bl.a. oprette og slette reservationer
Definition at line 10 of file Reservations.php.
Constructor & Destructor Documentation
__construct()
__construct (TecTools $TecTools)
Definition at line 36 of file Reservations.php.
References $TecTools.
Member Function Documentation
addReservation()
addReservation ()
Tilføjer en reservation for en bruger via POST request
Exceptions
Definition at line 137 of file Reservations.php.
References $userID, $userProduct, Logs\ADD_RESERVATION_TYPE_ID, RCMS\execute(), hasUserReachedMaxReservations(), and Helpers\setNotification().
deleteReservation()
deleteReservation ()
Sletter en reservation via POST request
Definition at line 97 of file Reservations.php.
References $userID, Logs\DELETE_RESERVATION_TYPE_ID, RCMS\execute(), Helpers\setNotification(), and userOwnsReservation().
getReservationCountForUser()
getReservationCountForUser (int $userID)
Returnerer hvor mange reservationer brugeren har
Parameters
int $userID
Returns
int
Definition at line 61 of file Reservations.php.
References $userID, and RCMS\execute().
Referenced by hasUserReachedMaxReservations().
hasUserReachedMaxReservations()
hasUserReachedMaxReservations (int $userID = 0)
Tjekker om en bruger har reserveret det antal værktøj som deres abonnement tillader
Parameters
int $userID
Returns
bool
Exceptions
Definition at line 72 of file Reservations.php.
References $userID, $userProduct, and getReservationCountForUser().
Referenced by addReservation().
isToolReserved()
isToolReserved (int $toolID, int $userID)
Tjekker om et værktøj er reserveret
Returnerer false hvis det er brugeren selv, $userID, som ejer reservationen
Parameters
int $toolID
int $userID
Returns
bool
Definition at line 51 of file Reservations.php.
References $userID, and RCMS\execute().
userOwnsReservation()
userOwnsReservation (int $reservationID) private
Tjekker om en bruger ejer en reservation
Parameters
int $reservationID
Returns
bool
Definition at line 119 of file Reservations.php.
References RCMS\execute().
Referenced by deleteReservation().
Field Documentation
$allowedEndpoints
array $allowedEndpoints static
Initial value:
= [
        'addReservation', 'deleteReservation'
    ]
Definition at line 27 of file Reservations.php.
$disableAutoLoading
bool $disableAutoLoading static
Forhindrer RCMS at loade denne klasse automatisk
Definition at line 20 of file Reservations.php.
$RCMS
RCMS $RCMS
Definition at line 14 of file Reservations.php.
$TecTools
TecTools $TecTools
Definition at line 34 of file Reservations.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
include/plugins/TecTools/Reservations.php