TecTools: TecTools Class Reference
TecTools Class Reference
Public Member Functions
__construct (RCMS $RCMS)
getToolByBarcode (string $barcode)
editTool ()
addTool ()
getToolByID (int $toolID)
cleanImagePath (string $path)
getToolByBarcodeAjax ()
getAllStores ()
getStoreLocations ()
getToolCountWithFilters ()
displayFrontPagePagination ()
displayToolCountMessage ()
getAllToolsWithFilters ()
getAllStatuses ()
handlePOSTEndpoints ()
Data Fields
RCMS $RCMS
Categories $Categories
Manufacturers $Manufacturers
Reservations $Reservations
CheckIns $CheckIns
Subscriptions $Subscriptions
Users $Users
string $TOOL_IMAGE_FOLDER
string $RELATIVE_TOOL_IMAGE_FOLDER
const TOOL_AVAILABLE_STATUS = 1
const TOOL_RESERVED_STATUS = 2
const TOOL_LOANED_OUT_STATUS = 3
const TOOL_NOT_IN_STOCK_STATUS = 4
const TOOL_DAMAGED_STATUS = 5
array $POSTClasses = []
Static Public Attributes
static array $allowedEndpoints
Private Member Functions
uploadImage (string $imageName, string $tmpName)
getFilterQueryString ()
getPaginationFilters ()
contactCustomerService ()
Private Attributes
const TOOLS_PER_PAGE = 8
Detailed Description
Class TecTools Denne klasse indeholder metoder som vedrører værktøj og butikker, samt meget andet, på TecTools siden Den indeholder metoder til bl.a. oprette, redigere og hente værktøj Klassen står også for at loade vores andre klasser som er nødvendige for at siden fungere
Definition at line 18 of file TecTools.php.
Constructor & Destructor Documentation
__construct()
__construct (RCMS $RCMS)
Definition at line 114 of file TecTools.php.
References $RCMS, RCMS\getRelativeUploadsFolder(), RCMS\getUploadsFolder(), and handlePOSTEndpoints().
Member Function Documentation
addTool()
addTool ()
Tilføjer et værktøj til databasen via en POST request
Returns
void
Exceptions
Exception
Returns
void
Definition at line 233 of file TecTools.php.
References $categories, Categories\addToolToCategory(), Logs\CREATE_TOOL_TYPE_ID, RCMS\execute(), Helpers\redirect(), Helpers\setNotification(), and uploadImage().
cleanImagePath()
cleanImagePath (string $path)
Sørger for at stien til billedet er korrekt, således at det kan udskrives på siden
Parameters
$path
Returns
string
Definition at line 295 of file TecTools.php.
Referenced by CheckIns\getCheckInAjax(), CheckIns\getCheckInsForMarquee(), and getToolByBarcodeAjax().
contactCustomerService()
contactCustomerService () private
Sender en mail til TecTools personalet En kunde kan kontakte TecTools personalet via kontakt siden
Definition at line 524 of file TecTools.php.
References $_SESSION, RCMS\getTemplateFolder(), Helpers\redirect(), Mailer\sendEmail(), Helpers\setNotification(), and siden.
displayFrontPagePagination()
displayFrontPagePagination ()
Udskriver links til forsiden så man kan skifte side og se flere værktøj
Definition at line 358 of file TecTools.php.
References $_GET, $pages, getFilterQueryString(), and getToolCountWithFilters().
displayToolCountMessage()
displayToolCountMessage ()
Udskriver beskeden på forsiden hvor der står "Viser 1 - x af x på side x"
Definition at line 380 of file TecTools.php.
References $_GET, and getToolCountWithFilters().
editTool()
editTool ()
Redigerer et værktøj via en POST request
Returns
void
Exceptions
Exception
Definition at line 145 of file TecTools.php.
References $categories, $category, Categories\addToolToCategory(), Helpers\array_equal(), Logs\EDIT_TOOL_TYPE_ID, RCMS\execute(), getToolByID(), Helpers\redirect(), Categories\removeAllCategoriesFromTool(), Helpers\setNotification(), and uploadImage().
getAllStatuses()
getAllStatuses ()
Henter alle statusser ud fra databasen
Returns
array
Definition at line 456 of file TecTools.php.
References RCMS\execute().
getAllStores()
getAllStores ()
Henter alle vores butikker ud af databasen
Returns
array
Definition at line 325 of file TecTools.php.
References RCMS\execute().
Referenced by getStoreLocations().
getAllToolsWithFilters()
getAllToolsWithFilters ()
Henter værktøj ud af databasen og filtrere på kategorier og søgetekst hvis det er valgt
Returns
array
Definition at line 439 of file TecTools.php.
References $tool, $tools, RCMS\execute(), Categories\getCategoriesForTool(), and getPaginationFilters().
getFilterQueryString()
getFilterQueryString () private
Bygger og formaterer de URL søge parametre vi bruger til at filtrere på forsiden Bruges også til paginering, så man kan skifte side og se flere værktøj Den string man får tilbage kunne f.eks. være "&search-text=test&only_in_stock=1"
Returns
string
Definition at line 396 of file TecTools.php.
Referenced by displayFrontPagePagination().
getPaginationFilters()
getPaginationFilters () private
Returnerer de forskellige filtre der kan bruges til søgning af værktøj
Returns
array
Definition at line 426 of file TecTools.php.
References $_GET, and $category.
Referenced by getAllToolsWithFilters(), and getToolCountWithFilters().
getStoreLocations()
getStoreLocations ()
Returnerer et array med lokationer for vores butikker
Returns
array
Definition at line 333 of file TecTools.php.
References getAllStores().
getToolByBarcode()
getToolByBarcode (string $barcode)
Henter et værktøj ud fra databasen hvor værktøjets stregkode er lig $barcode
Parameters
string $barcode
Returns
array|null
Definition at line 136 of file TecTools.php.
References RCMS\execute().
Referenced by CheckIns\checkIn(), and getToolByBarcodeAjax().
getToolByBarcodeAjax()
getToolByBarcodeAjax ()
Henter et værktøj ud af databasen via stregkoden, og udskriver resultatet i JSON. Via POST request
Definition at line 303 of file TecTools.php.
References $result, $tool, cleanImagePath(), getToolByBarcode(), Helpers\outputAJAXResult(), and Logs\SCAN_TYPE_ID.
getToolByID()
getToolByID (int $toolID)
Henter et værktøj ud fra databasen
Parameters
int $toolID
Returns
array|false
Definition at line 278 of file TecTools.php.
References $tool, RCMS\execute(), and Categories\getCategoriesForTool().
Referenced by CheckIns\checkOut(), editTool(), and CheckIns\getCheckInAjax().
getToolCountWithFilters()
getToolCountWithFilters ()
Returnerer antal af værktøj der er i databasen (med filtre), til brug ved pagination
Returns
int
Definition at line 349 of file TecTools.php.
References RCMS\execute(), and getPaginationFilters().
Referenced by displayFrontPagePagination(), and displayToolCountMessage().
handlePOSTEndpoints()
handlePOSTEndpoints ()
Denne metode tjekker, om $_POST arrayet indeholder navnet på en metode i denne klasse eller de andre TecTools underklasser, tjekker derefter om det er en af de tilladte endpoints, og eksekvere efterfølgende metoden hvis det er tilfældet
Det er endda muligt for handlePOSTEndpoints at overdrage funktionsparametre til målfunktionen
Definition at line 469 of file TecTools.php.
References $allowedEndpoints, and Helpers\setNotification().
Referenced by __construct().
uploadImage()
uploadImage (string $imageName, string $tmpName) private
Uploader et billede for et værktøj via en POST request, bruger $_FILES array
Parameters
string $imageName
string $tmpName
Returns
string|false
Exceptions
Exception
Definition at line 204 of file TecTools.php.
References $_SESSION.
Referenced by addTool(), and editTool().
Field Documentation
$allowedEndpoints
array $allowedEndpoints static
Initial value:
= [
        'addTool', 'editTool', 'getToolByBarcodeAjax', 'contactCustomerService'
    ]
Definition at line 104 of file TecTools.php.
$Categories
Categories $Categories
Definition at line 27 of file TecTools.php.
$CheckIns
CheckIns $CheckIns
Definition at line 42 of file TecTools.php.
$Manufacturers
Manufacturers $Manufacturers
Definition at line 32 of file TecTools.php.
$POSTClasses
array $POSTClasses = []
Array over klasser som indeholder metoder som skal kunne kaldes via POST requests
Definition at line 112 of file TecTools.php.
$RCMS
RCMS $RCMS
Definition at line 22 of file TecTools.php.
Referenced by __construct().
$RELATIVE_TOOL_IMAGE_FOLDER
string $RELATIVE_TOOL_IMAGE_FOLDER
Relative sti til mappen hvor billeder af værktøj ligger
Definition at line 64 of file TecTools.php.
$Reservations
Reservations $Reservations
Definition at line 37 of file TecTools.php.
$Subscriptions
Subscriptions $Subscriptions
Definition at line 47 of file TecTools.php.
$TOOL_IMAGE_FOLDER
string $TOOL_IMAGE_FOLDER
Absolutte sti til mappen hvor billeder af værktøj ligger
Definition at line 58 of file TecTools.php.
$Users
Users $Users
Definition at line 52 of file TecTools.php.
TOOL_AVAILABLE_STATUS
int TOOL_AVAILABLE_STATUS = 1
Status værdi for værktøj som er på lager
Status værdi for værktøj som er udlånt
Status værdi for værktøj som ikke er på lager (ex. demo vare, udgået, udsolgt)
Status værdi for værktøj som er beskadiget
Definition at line 74 of file TecTools.php.
TOOL_DAMAGED_STATUS
const TOOL_DAMAGED_STATUS = 5
Definition at line 97 of file TecTools.php.
TOOL_LOANED_OUT_STATUS
const TOOL_LOANED_OUT_STATUS = 3
Definition at line 85 of file TecTools.php.
TOOL_NOT_IN_STOCK_STATUS
const TOOL_NOT_IN_STOCK_STATUS = 4
Definition at line 91 of file TecTools.php.
TOOL_RESERVED_STATUS
const TOOL_RESERVED_STATUS = 2
Status værdi for værktøj som er reserveret
Definition at line 79 of file TecTools.php.
TOOLS_PER_PAGE
const TOOLS_PER_PAGE = 8 private
Antal værktøj der bliver vist på forsiden per side
Definition at line 69 of file TecTools.php.
The documentation for this class was generated from the following file:
include/plugins/TecTools/TecTools.php