TecTools: StripeWrapper Class Reference
StripeWrapper Class Reference
Public Member Functions
__construct (RCMS $RCMS, string $secretStripeKey)
getStripeClient ()
createCustomer (array $params)
removeCustomer (string $customerID)
editCustomer (string $customerID, array $params)
isPremiumPlan (array $product, float $premiumPrice)
getPlan (string $productID)
getCustomerPaymentCardID (string $customerID)
createPaymentIntent (string $customerID, float $amount, string $cardID, string $description='')
getSubscriptionID (string $customerID)
getSubscription (string $customerID)
getStripeProduct (string $productID)
Data Fields
RCMS $RCMS
Private Attributes
StripeClient $stripe
Detailed Description
Class StripeWrapper Denne klasse fungerer som en wrapper til Stripe API'et. Den indeholder metoder som gør det nemmere at arbejde med API'et og reducere mængden af kode der skal skrives. Den indeholder bl.a. metoder til at oprette, redigere og slette kunder og hente produkter
Definition at line 19 of file StripeWrapper.php.
Constructor & Destructor Documentation
__construct()
__construct (RCMS $RCMS, string $secretStripeKey)
StripeWrapper constructor.
Parameters
RCMS $RCMS
string $secretStripeKey
Definition at line 35 of file StripeWrapper.php.
References $RCMS.
Member Function Documentation
createCustomer()
createCustomer (array $params)
Opretter en kunde i Stripe
Reference: https://stripe.com/docs/api/customers/create
Parameters
array $params
Returns
Customer
Exceptions
ApiErrorException
Definition at line 56 of file StripeWrapper.php.
References getStripeClient().
createPaymentIntent()
createPaymentIntent (string $customerID, float $amount, string $cardID, string $description = '')
Hæver penge fra et betalingskort og returnerer ID'et for betalingen
Parameters
string $customerID
float $amount
string $cardID
string $description
Returns
string
Exceptions
ApiErrorException
Definition at line 205 of file StripeWrapper.php.
References getStripeClient().
editCustomer()
editCustomer (string $customerID, array $params)
Ændrer brugeroplysninger for en kunde
Parameters
string $customerID Kundens ID
array $params
Returns
Customer
Exceptions
ApiErrorException
Definition at line 77 of file StripeWrapper.php.
References getStripeClient().
getCustomerPaymentCardID()
getCustomerPaymentCardID (string $customerID)
Returnerer betalingsmetode ID'et for en kundes kort
Parameters
string $customerID
Returns
false|string
Exceptions
ApiErrorException
Definition at line 181 of file StripeWrapper.php.
References getStripeClient().
getPlan()
getPlan (string $productID)
Returnerer en Stripe plan
Reference for plan: https://stripe.com/docs/api/plans
Reference for produkt: https://stripe.com/docs/api/products
Parameters
string $productID ID på et Stripe produkt, F.eks. prod_HQWzfyxLdAjwWo
Returns
\Stripe\StripeObject[]|null
Exceptions
ApiErrorException
Definition at line 162 of file StripeWrapper.php.
References $productID, and getStripeClient().
getStripeClient()
getStripeClient ()
Returnerer den instans af StripeClient som er blevet lavet i __construct
Returns
StripeClient
Definition at line 44 of file StripeWrapper.php.
References $stripe.
Referenced by createCustomer(), createPaymentIntent(), editCustomer(), getCustomerPaymentCardID(), getPlan(), getSubscription(), getSubscriptionID(), and removeCustomer().
getStripeProduct()
getStripeProduct (string $productID)
Returnerer et Stripe produkt
Reference for produkt: https://stripe.com/docs/api/products
Parameters
string $productID ID på et Stripe produkt, F.eks. prod_HQWzfyxLdAjwWo
Returns
false|array
Exceptions
ApiErrorException
Definition at line 248 of file StripeWrapper.php.
References $product, and $productID.
getSubscription()
getSubscription (string $customerID)
Returnerer abonnementet for kunden med $customerID
Parameters
string $customerID Kundens ID
Returns
\Stripe\StripeObject
Exceptions
ApiErrorException
Definition at line 236 of file StripeWrapper.php.
References getStripeClient().
getSubscriptionID()
getSubscriptionID (string $customerID)
Returnerer ID'et for et abonnement for kunden med $customerID
Parameters
string $customerID Kundens ID
Returns
string|null
Exceptions
ApiErrorException
Definition at line 225 of file StripeWrapper.php.
References getStripeClient().
isPremiumPlan()
isPremiumPlan (array $product, float $premiumPrice)
Tjekker om prisen for et produkt er over X kroner
Parameters
array $product
float $premiumPrice
Returns
bool
Definition at line 121 of file StripeWrapper.php.
References $product.
removeCustomer()
removeCustomer (string $customerID)
Sletter en kunde i Stripe
Parameters
string $customerID Kundens ID
Returns
Customer
Exceptions
ApiErrorException
Definition at line 66 of file StripeWrapper.php.
References getStripeClient().
Field Documentation
$RCMS
RCMS $RCMS
Definition at line 23 of file StripeWrapper.php.
Referenced by __construct().
$stripe
StripeClient $stripe private
Definition at line 28 of file StripeWrapper.php.
Referenced by getStripeClient().
The documentation for this class was generated from the following file:
include/StripeWrapper.php