TecTools: Helpers Class Reference
Helpers Class Reference
Public Member Functions
__construct (RCMS $RCMS)
isFrontPage ()
Static Public Member Functions
static setNotification (string $title='', string $message='', string $type='success')
static guidv4 ()
static getHTTPHost ()
static array_equal (array $a, array $b)
static super_unique (array $array, string $key)
static outputAJAXResult (int $status, array $result)
static escape (string $str)
static customLocation ()
static isFutureDateTimeString (string $dateTimeString)
static formatFirstLastName (string $firstName, string $lastName)
static redirect ($page)
static outputError (string $error, string $htmlTag='p', bool $centerAlign=false)
Data Fields
RCMS $RCMS
Detailed Description
Class Helpers Denne klasse indeholder hjælpe funktioner. Bl.a. til at omdirigere brugeren, sætte notifikationer osv.
Definition at line 10 of file Helpers.php.
Constructor & Destructor Documentation
__construct()
__construct (RCMS $RCMS)
Definition at line 13 of file Helpers.php.
References $RCMS.
Member Function Documentation
array_equal()
static array_equal (array $a, array $b) static
Returnerer true hvis begge arrays, $a og $b, er ens, ellers false.
Parameters
array $a
array $b
Returns
bool
Definition at line 74 of file Helpers.php.
Referenced by TecTools\editTool().
customLocation()
static customLocation () static
Omdirigerer en bruger til den URL der blev postet, hvis den er sat
Definition at line 129 of file Helpers.php.
References escape().
Referenced by CheckIns\checkOut(), and Reservations\deleteReservation().
escape()
static escape (string $str) static
Fjerner HTML fra en string
Parameters
string $str
Returns
string
Definition at line 122 of file Helpers.php.
Referenced by customLocation().
formatFirstLastName()
static formatFirstLastName (string $firstName, string $lastName) static
Formaterer fornavn og efternavn til et fuldt navn
Parameters
string $firstName
string $lastName
Returns
string
Definition at line 153 of file Helpers.php.
Referenced by CheckIns\sendFinePaidEmail(), Cronjobs\sendMailOldReservationDeleted(), CheckIns\sendNewCheckInEmail(), and CheckIns\sendNewFineEmail().
getHTTPHost()
static getHTTPHost () static
Returnerer HTTP host med protokol Ex. https://tectools.virtusb.com
Returns
string
Definition at line 64 of file Helpers.php.
Referenced by Login\resetPassword(), Cronjobs\sendMailOldReservationDeleted(), CheckIns\sendNewCheckInEmail(), and CheckIns\sendNewFineEmail().
guidv4()
static guidv4 () static
Genererer et GUID Version 4 på 36 karakterer (med bindestreger)
Returns
string
Exceptions
Exception
Definition at line 50 of file Helpers.php.
Referenced by Login\resetPassword().
isFrontPage()
isFrontPage ()
Returnerer true hvis brugeren er på forsiden, ellers false
Returns
bool
Definition at line 21 of file Helpers.php.
References $_GET, RCMS\getHomeFolder(), and RCMS\getMySQLi().
isFutureDateTimeString()
static isFutureDateTimeString (string $dateTimeString) static
Laver en ny DateTime ud af $dateTimeString, og returnerer true hvis den DateTime er i fremtiden, ellers false
Parameters
string $dateTimeString
Returns
bool
Exceptions
Exception
Definition at line 143 of file Helpers.php.
outputAJAXResult()
static outputAJAXResult (int $status, array $result) static
Returnerer data til klienten i JSON format
Parameters
int $status HTTP status kode, ex. 200 eller 404 osv.
array $result
Returns
void
Exceptions
JsonException
Definition at line 105 of file Helpers.php.
References $result.
Referenced by CheckIns\checkIn(), CheckIns\getCheckInAjax(), CheckIns\getCheckInComment(), TecTools\getToolByBarcodeAjax(), Subscriptions\newSubscription(), and CheckIns\saveCheckInComment().
outputError()
static outputError (string $error, string $htmlTag = 'p', bool $centerAlign = false) static
Udskriver en fejl på siden
Parameters
string $error Beskeden som brugeren skal have vist
string $htmlTag Hvilket element der skal udskrives, f.eks. p for paragraph eller h1
bool $centerAlign Kontrollere om beskeden skal centreres
Returns
void
Definition at line 174 of file Helpers.php.
redirect()
static redirect ($page) static
Omdirigerer brugeren
Parameters
$page
Definition at line 161 of file Helpers.php.
Referenced by Categories\addCategory(), TecToolsCategories\addCategory(), Manufacturers\addManufacturer(), TecTools\addTool(), TecTools\contactCustomerService(), Login\createUser(), Users\deleteUser(), Categories\editCategory(), TecToolsCategories\editCategory(), Manufacturers\editManufacturer(), TecTools\editTool(), Users\editUser(), RCMS\fixURLQueryQuestionMarks(), Login\log_in(), CheckIns\payFine(), Login\resetPassword(), and Login\resetPasswordVerify().
setNotification()
static setNotification (string $title = '', string $message = '', string $type = 'success') static
Sætter en cookie i browseren, som javascript i klienten finder og viser notifikationen
Parameters
$title
$message
string $type
Exceptions
JsonException
Definition at line 34 of file Helpers.php.
Referenced by Categories\addCategory(), TecToolsCategories\addCategory(), Manufacturers\addManufacturer(), Reservations\addReservation(), TecTools\addTool(), Subscriptions\cancelSubscription(), CheckIns\checkOut(), TecTools\contactCustomerService(), Categories\deleteCategory(), Manufacturers\deleteManufacturer(), Reservations\deleteReservation(), Users\deleteUser(), Categories\editCategory(), TecToolsCategories\editCategory(), Manufacturers\editManufacturer(), TecTools\editTool(), Users\editUser(), Base\handlePOSTEndpoints(), TecTools\handlePOSTEndpoints(), Login\log_in(), Subscriptions\newSubscription(), CheckIns\payFine(), Login\resetPassword(), Login\resetPasswordVerify(), and Subscriptions\upgradeDowngradeSubscription().
super_unique()
static super_unique (array $array, string $key) static
Funktion til at gøre et array unikt, ligesom den indbygget array_unique funktion, men denne virker på flerdimensionelle arrays
Parameters
array $array
string $key
Returns
array
Definition at line 87 of file Helpers.php.
Field Documentation
$RCMS
RCMS $RCMS
Definition at line 11 of file Helpers.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
include/Helpers.php