TecTools: CheckIns Class Reference
CheckIns Class Reference
Public Member Functions
__construct (TecTools $TecTools)
saveCheckInComment ()
getCheckInComment ()
getCheckInAjax ()
checkIn ()
hasUserReachedMaxCheckouts (int $userID=0)
checkOut ()
getCountOfUnpaidFinesForUser (?int $userID=null)
getFineByHash (string $hash)
payFine ()
isToolCheckedIn (int $toolID)
getCheckInCountForUser (int $userID)
getCheckInsForMarquee ()
Data Fields
RCMS $RCMS
TecTools $TecTools
Static Public Attributes
static bool $disableAutoLoading
static array $allowedEndpoints
Private Member Functions
getCheckIn (int $checkInID)
getCheckInByBarcode (int $barcode)
sendNewCheckInEmail (int $checkInID)
addFineToCheckIn (array $checkIn, float $fineAmount, string $fineComment)
getFineByID (int $fineID)
markFineAsPaid (int $fineID, string $paymentIntentID)
sendFinePaidEmail (array $fine)
sendNewFineEmail (int $fineID, array $checkIn, float $fineAmount, string $fineComment)
Detailed Description
Class CheckIns Denne klasse indeholder metoder som vedrører Tjek Ind og Tjek Ud funktionalitet på TecTools siden Den indeholder metoder til bl.a. låne værktøj og returnere værktøj på lager igen
Definition at line 10 of file CheckIns.php.
Constructor & Destructor Documentation
__construct()
__construct (TecTools $TecTools)
Definition at line 38 of file CheckIns.php.
References $TecTools.
Member Function Documentation
addFineToCheckIn()
addFineToCheckIn (array $checkIn, float $fineAmount, string $fineComment) private
Denne metode tilføjer en bøde for en udlejning
Parameters
array $checkIn
float $fineAmount
string $fineComment
Returns
int
Definition at line 327 of file CheckIns.php.
References $userID, RCMS\execute(), and Logs\FINE_ISSUED_TYPE_ID.
Referenced by checkOut().
checkIn()
checkIn ()
Tilføj et Check-In af et værktøj på en bruger, via POST request
Returns
void
Exceptions
Definition at line 149 of file CheckIns.php.
References $tool, $userID, $userProduct, Logs\CHECK_IN_TYPE_ID, RCMS\execute(), TecTools\getToolByBarcode(), hasUserReachedMaxCheckouts(), isToolCheckedIn(), Helpers\outputAJAXResult(), and sendNewCheckInEmail().
checkOut()
checkOut ()
Tjekker et værktøj ud via POST request Kan kun bruges af administratorer
Definition at line 279 of file CheckIns.php.
References $tool, addFineToCheckIn(), Logs\CHECK_OUT_TYPE_ID, Helpers\customLocation(), RCMS\execute(), getCheckIn(), TecTools\getToolByID(), sendNewFineEmail(), and Helpers\setNotification().
getCheckIn()
getCheckIn (int $checkInID) private
Returnerer et CheckIn fra databasen via ID
Parameters
$checkInID
Returns
array|false
Definition at line 95 of file CheckIns.php.
References RCMS\execute().
Referenced by checkOut(), getCheckInAjax(), getCheckInComment(), saveCheckInComment(), and sendNewCheckInEmail().
getCheckInAjax()
getCheckInAjax ()
Returnerer et CheckIn fra databasen via POST request
Definition at line 111 of file CheckIns.php.
References $tool, TecTools\cleanImagePath(), getCheckIn(), getCheckInByBarcode(), TecTools\getToolByID(), and Helpers\outputAJAXResult().
getCheckInByBarcode()
getCheckInByBarcode (int $barcode) private
Returnerer et CheckIn fra databasen via stregkode
Parameters
int $barcode
Returns
array|false
Definition at line 104 of file CheckIns.php.
References RCMS\execute().
Referenced by getCheckInAjax().
getCheckInComment()
getCheckInComment ()
Henter kommentaren for en specifik udlejning og udskriver den via POST request
Definition at line 73 of file CheckIns.php.
References $userID, getCheckIn(), and Helpers\outputAJAXResult().
getCheckInCountForUser()
getCheckInCountForUser (int $userID)
Returnerer hvor mange udlån brugeren har
Parameters
int $userID
Returns
int
Definition at line 508 of file CheckIns.php.
References $userID, and RCMS\execute().
Referenced by hasUserReachedMaxCheckouts().
getCheckInsForMarquee()
getCheckInsForMarquee ()
Returnerer udlejninger som skal vises nederst på forsiden i det glidende element, marquee
Returns
array
Definition at line 517 of file CheckIns.php.
References TecTools\cleanImagePath(), and RCMS\execute().
getCountOfUnpaidFinesForUser()
getCountOfUnpaidFinesForUser (?int $userID = null)
Returnerer antal af ubetalte bøder brugeren har
Parameters
int | null $userID
Returns
int
Definition at line 312 of file CheckIns.php.
References $userID, and RCMS\execute().
getFineByHash()
getFineByHash (string $hash)
Henter en bøde ud fra databasen via dens hash
Parameters
string $hash
Returns
array|null
Definition at line 357 of file CheckIns.php.
References $fine, and RCMS\execute().
Referenced by payFine().
getFineByID()
getFineByID (int $fineID) private
Henter en bøde ud fra databasen via ID
Parameters
int $fineID
Returns
array|null
Definition at line 342 of file CheckIns.php.
References $fine, and RCMS\execute().
Referenced by sendNewFineEmail().
hasUserReachedMaxCheckouts()
hasUserReachedMaxCheckouts (int $userID = 0)
Tjekker om en bruger har udlånt det antal værktøj som deres abonnement tillader
Parameters
int $userID
Returns
bool
Exceptions
Definition at line 253 of file CheckIns.php.
References $userID, $userProduct, and getCheckInCountForUser().
Referenced by checkIn().
isToolCheckedIn()
isToolCheckedIn (int $toolID)
Tjekker om et værktøj er udlånt
Parameters
int $toolID
Returns
bool
Definition at line 498 of file CheckIns.php.
References RCMS\execute().
Referenced by checkIn().
markFineAsPaid()
markFineAsPaid (int $fineID, string $paymentIntentID) private
Sætter en bøde til at være betalt
Parameters
int $fineID
string $paymentIntentID
Definition at line 399 of file CheckIns.php.
References RCMS\execute().
Referenced by payFine().
payFine()
payFine ()
Betaler en bøde via POST request
Definition at line 370 of file CheckIns.php.
References $fine, $paymentHash, Logs\FINE_PAID_TYPE_ID, getFineByHash(), markFineAsPaid(), Helpers\redirect(), sendFinePaidEmail(), and Helpers\setNotification().
saveCheckInComment()
saveCheckInComment ()
Gemmer en kommentar for en udlejning via POST request
Definition at line 48 of file CheckIns.php.
References $userID, Logs\ADD_COMMENT_TYPE_ID, Logs\EDIT_COMMENT_TYPE_ID, RCMS\execute(), getCheckIn(), and Helpers\outputAJAXResult().
sendFinePaidEmail()
sendFinePaidEmail (array $fine) private
Denne metode sender en email til kunden, og informerer dem om at de har betalt en bøde
Parameters
array $fine
Definition at line 407 of file CheckIns.php.
References $fine, $user, Helpers\formatFirstLastName(), RCMS\getTemplateFolder(), and Mailer\sendEmail().
Referenced by payFine().
sendNewCheckInEmail()
sendNewCheckInEmail (int $checkInID) private
Denne metode sender en email til kunden, og informerer om deres nye lån
Parameters
int $checkInID
Definition at line 207 of file CheckIns.php.
References $tool, $user, Helpers\formatFirstLastName(), getCheckIn(), Helpers\getHTTPHost(), RCMS\getTemplateFolder(), TecTools\getToolByID(), and Mailer\sendEmail().
Referenced by checkIn().
sendNewFineEmail()
sendNewFineEmail (int $fineID, array $checkIn, float $fineAmount, string $fineComment) private
Denne metode sender en email til kunden, og informerer dem om at de har fået en bøde
Parameters
int $fineID
array $checkIn
float $fineAmount
string $fineComment
Definition at line 446 of file CheckIns.php.
References $fine, $tool, $user, Helpers\formatFirstLastName(), getFineByID(), Helpers\getHTTPHost(), RCMS\getTemplateFolder(), TecTools\getToolByID(), and Mailer\sendEmail().
Referenced by checkOut().
Field Documentation
$allowedEndpoints
array $allowedEndpoints static
Initial value:
= [
        'checkIn', 'checkOut',
        'getCheckInComment', 'saveCheckInComment', 'getCheckInAjax',
        'payFine'
    ]
Definition at line 27 of file CheckIns.php.
$disableAutoLoading
bool $disableAutoLoading static
Forhindrer RCMS at loade denne klasse automatisk
Definition at line 20 of file CheckIns.php.
$RCMS
RCMS $RCMS
Definition at line 14 of file CheckIns.php.
$TecTools
TecTools $TecTools
Definition at line 36 of file CheckIns.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
include/plugins/TecTools/CheckIns.php