TecTools: Subscriptions Class Reference
Subscriptions Class Reference
Public Member Functions
__construct (TecTools $TecTools)
getSubName ()
cancelSubscription ()
upgradeDowngradeSubscription ()
newSubscription ()
Data Fields
RCMS $RCMS
TecTools $TecTools
Static Public Attributes
static bool $disableAutoLoading
static array $allowedEndpoints
Private Member Functions
setSubName (string $subName)
Detailed Description
Class Subscriptions Denne klasse indeholder metoder som vedrører abonnementer på TecTools siden Den indeholder metoder til bl.a. oprette, opgradere, nedgradere og annullere abonnementer
Definition at line 10 of file Subscriptions.php.
Constructor & Destructor Documentation
__construct()
__construct (TecTools $TecTools)
Definition at line 36 of file Subscriptions.php.
References $TecTools.
Member Function Documentation
cancelSubscription()
cancelSubscription ()
Sender en API request til Stripe, og annullerer brugerens abonnement
Exceptions
Definition at line 67 of file Subscriptions.php.
References Logs\CANCEL_SUBSCRIPTION_TYPE_ID, Helpers\setNotification(), and setSubName().
getSubName()
getSubName ()
Returnerer navnet på brugerens abonnement
Returns
bool|string
Definition at line 47 of file Subscriptions.php.
References $_SESSION.
newSubscription()
newSubscription ()
Sender en API request til Stripe, og opretter et abonnement for brugeren via POST request
Exceptions
Definition at line 123 of file Subscriptions.php.
References Logs\NEW_SUBSCRIPTION_TYPE_ID, Helpers\outputAJAXResult(), Helpers\setNotification(), and setSubName().
setSubName()
setSubName (string $subName) private
Gemmer navnet på abonnementet som brugeren har
Parameters
$subName
Definition at line 55 of file Subscriptions.php.
References $_SESSION, $userID, and RCMS\execute().
Referenced by cancelSubscription(), newSubscription(), and upgradeDowngradeSubscription().
upgradeDowngradeSubscription()
upgradeDowngradeSubscription ()
Sender en API request til Stripe, og opgraderer eller nedgraderer brugerens abonnement via POST request
Exceptions
Definition at line 90 of file Subscriptions.php.
References Logs\DOWNGRADE_SUBSCRIPTION_TYPE_ID, Helpers\setNotification(), setSubName(), and Logs\UPGRADE_SUBSCRIPTION_TYPE_ID.
Field Documentation
$allowedEndpoints
array $allowedEndpoints static
Initial value:
= [
        'newSubscription', 'cancelSubscription', 'upgradeDowngradeSubscription'
    ]
Definition at line 27 of file Subscriptions.php.
$disableAutoLoading
bool $disableAutoLoading static
Forhindrer RCMS at loade denne klasse automatisk
Definition at line 20 of file Subscriptions.php.
$RCMS
RCMS $RCMS
Definition at line 14 of file Subscriptions.php.
$TecTools
TecTools $TecTools
Definition at line 34 of file Subscriptions.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
include/plugins/TecTools/Subscriptions.php