TecTools: Cronjobs Class Reference
Cronjobs Class Reference
Public Member Functions
__construct (RCMS $RCMS)
deleteOldReservations ()
Data Fields
RCMS $RCMS
Private Member Functions
sendMailOldReservationDeleted (array $reservation)
Detailed Description
Class Cronjobs I denne klasse opretter vi en metode til hvert cronjob, vi gerne vil have der skal køre på TecTools siden. Efter man har lavet metoden, skal den tilføjes til "Cron" arrayet i RCMS.
Definition at line 10 of file Cronjobs.php.
Constructor & Destructor Documentation
__construct()
__construct (RCMS $RCMS)
Definition at line 13 of file Cronjobs.php.
References $RCMS, and deleteOldReservations().
Member Function Documentation
deleteOldReservations()
deleteOldReservations ()
Tilføjer cronjob til at slette gamle reservationer Køres hvert 5. minut
Definition at line 23 of file Cronjobs.php.
References RCMS\execute(), RCMS\getCron(), and sendMailOldReservationDeleted().
Referenced by __construct().
sendMailOldReservationDeleted()
sendMailOldReservationDeleted (array $reservation) private
Sender en mail til brugeren, som forklarer at deres reservation er blevet slettet
Parameters
array $reservation
Definition at line 43 of file Cronjobs.php.
References Helpers\formatFirstLastName(), Helpers\getHTTPHost(), RCMS\getTemplateFolder(), and Mailer\sendEmail().
Referenced by deleteOldReservations().
Field Documentation
$RCMS
RCMS $RCMS
Definition at line 11 of file Cronjobs.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
include/plugins/TecTools/Cronjobs.php