TecTools: Users Class Reference
Users Class Reference
Public Member Functions
__construct (TecTools $TecTools)
getStripeID ()
getSubName ()
getUserProduct (int $userID)
getUserByID (int $userID)
getUserByEmail (string $email)
authorizeUser (int $userID)
Public Member Functions inherited from Base
__construct ()
handlePOSTEndpoints ()
Data Fields
RCMS $RCMS
TecTools $TecTools
Static Public Attributes
static bool $disableAutoLoading
static array $allowedEndpoints
Static Public Attributes inherited from Base
static array $allowedEndpoints = []
Protected Member Functions
deleteUser ()
editUser ()
Private Member Functions
editCustomerInStripe (string $stripeCustomerID, string $firstname, string $lastname, string $email, string $phone, string $address, string $zipcode, string $city)
Detailed Description
Class Users Denne klasse indeholder metoder som vedrører brugere på TecTools siden Den indeholder metoder til bl.a. redigere og slette brugere, og til at hente brugerens abonnement
Definition at line 10 of file Users.php.
Constructor & Destructor Documentation
__construct()
__construct (TecTools $TecTools)
Definition at line 31 of file Users.php.
References $TecTools.
Member Function Documentation
authorizeUser()
authorizeUser (int $userID)
Returnerer false, hvis $userID ikke er det samme som brugerens ID i databasen og brugeren ikke er personale.
Personale kan ændre på alle brugere, så $userID må i de tilfælde godt være et andet ID end det som står i databasen.
Metoden returnerer altid false hvis brugeren ikke er logget ind
Parameters
int $userID
Returns
bool
Definition at line 250 of file Users.php.
References $userID.
Referenced by editUser().
deleteUser()
deleteUser () protected
Sletter en bruger via POST request Tjekker om brugeren stadig har aktive udlejninger Hvis brugeren har et abonnement, opsiges det
Exceptions
Definition at line 60 of file Users.php.
References Logs\DELETE_USER_TYPE_ID, RCMS\execute(), getStripeID(), Helpers\redirect(), and Helpers\setNotification().
editCustomerInStripe()
editCustomerInStripe (string $stripeCustomerID, string $firstname, string $lastname, string $email, string $phone, string $address, string $zipcode, string $city) private
Wrapper metode til at redigere en brugers oplysninger i Stripe
Parameters
string $stripeCustomerID
string $firstname
string $lastname
string $email
string $phone
string $address
string $zipcode
string $city
Exceptions
Definition at line 216 of file Users.php.
Referenced by editUser().
editUser()
editUser () protected
Redigerer en bruger via en POST request Bruges både når almindelige brugere ændre deres profil, og når personale ændre på andre brugeres profil
Returns
void
Exceptions
Definition at line 145 of file Users.php.
References $user, $userID, authorizeUser(), editCustomerInStripe(), RCMS\execute(), getUserByID(), Helpers\redirect(), and Helpers\setNotification().
getStripeID()
getStripeID ()
Returnerer brugerens Stripe Customer ID
Returns
bool|string
Definition at line 42 of file Users.php.
Referenced by deleteUser().
getSubName()
getSubName ()
Returnerer brugerens abonnement navn
Returns
bool|string
Definition at line 50 of file Users.php.
getUserByEmail()
getUserByEmail (string $email)
Henter en bruger ud af databasen via deres e-mail
Parameters
string $email
Returns
bool|array
Definition at line 133 of file Users.php.
References RCMS\execute().
getUserByID()
getUserByID (int $userID)
Henter en bruger ud fra databasen
Parameters
int $userID ID på den bruger som skal hentes ud
Returns
array|null
Definition at line 123 of file Users.php.
References $userID, and RCMS\execute().
Referenced by editUser(), and getUserProduct().
getUserProduct()
getUserProduct (int $userID)
Returnerer brugerens abonnement
Parameters
int $userID
Returns
array|bool
Exceptions
Definition at line 97 of file Users.php.
References $productID, $user, $userProduct, and getUserByID().
Field Documentation
$allowedEndpoints
array $allowedEndpoints static
Initial value:
= [
        'editUser', 'deleteUser'
    ]
Definition at line 22 of file Users.php.
$disableAutoLoading
bool $disableAutoLoading static
Forhindrer RCMS at loade denne klasse automatisk
Definition at line 20 of file Users.php.
$RCMS
RCMS $RCMS
Definition at line 14 of file Users.php.
$TecTools
TecTools $TecTools
Definition at line 29 of file Users.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
include/plugins/TecTools/Users.php