TecTools: RCMS Class Reference
RCMS Class Reference
Public Member Functions
__construct (string $host, string $user, string $pass, string $database, string $homefolder, string $templatefolder, string $uploadsfolder, string $secretStripeKey, string $environment='')
getUploadsFolder ()
getRelativeUploadsFolder ()
getHomeFolder ()
getTemplateFolder ()
getMySQLi ()
connect ()
execute (string $query, array $parameters=null)
getRequestedPage ()
getCron ()
closeRCMS ()
Static Public Member Functions
static fixURLQueryQuestionMarks ()
Data Fields
Helpers $Helpers
Template $Template
Login $Login
Logs $Logs
StripeWrapper $StripeWrapper
Mailer $Mailer
Private Member Functions
recursive_require_plugins (string $path)
shouldAutoLoad ($file)
instantiatePlugins ()
newGlobal (string $name, object $obj)
Private Attributes
string $host
string $user
string $pass
string $database
mysqli $mysqli
Cron $Cron = null
string $homefolder
string $templatefolder
string $uploadsfolder
string $relativeUploadsFolder
array $pluginsToLoad = []
Detailed Description
Class RCMS Denne klasse er entry-pointet for enhver webside der bruger RCMS-systemet. Klassen står for at forbinde til MySQL og for at loade andre nødvendige klasser. Den indeholder "execute" metoden, som står for at eksekvere SQL på en sikker måde, ved at benytte parametre og Prepared Statements
Definition at line 20 of file RCMS.php.
Constructor & Destructor Documentation
__construct()
__construct (string $host, string $user, string $pass, string $database, string $homefolder, string $templatefolder, string $uploadsfolder, string $secretStripeKey, string $environment = '')
Definition at line 118 of file RCMS.php.
References $database, $homefolder, $host, $pass, $templatefolder, $uploadsfolder, $user, connect(), instantiatePlugins(), recursive_require_plugins(), and Cron\runCronJobs().
Member Function Documentation
closeRCMS()
closeRCMS ()
Lukker for en RCMS instans Bruges til development og testing
Definition at line 357 of file RCMS.php.
References $_SESSION.
Referenced by LoginTest\tearDown().
connect()
connect ()
Opretter forbindelse til MySQL databasen
Returns
void
Definition at line 287 of file RCMS.php.
Referenced by __construct().
execute()
execute (string $query, array $parameters = null)
Eksekvere en MySQL query og bruger Prepared Statements for at undgå SQL injection
Parameters
string $query En MySQL query, f.eks. "SELECT * FROM Users"
null | array $parameters Et array af typer og parametre, f.eks. ['ssi', $username, $firstname, $userID] - første element er en string over typer (s for string, i for int), efterfølgende elementer er variabler givet med reference (& symbolet betyder reference pass-by-reference)
Returns
mysqli_result|void
Definition at line 299 of file RCMS.php.
Referenced by Categories\addCategory(), Logs\addLog(), Manufacturers\addManufacturer(), Reservations\addReservation(), TecTools\addTool(), Categories\addToolToCategory(), Categories\categoryExists(), CheckIns\checkIn(), CheckIns\checkOut(), Login\createUser(), Categories\deleteCategory(), Manufacturers\deleteManufacturer(), Cronjobs\deleteOldReservations(), Reservations\deleteReservation(), Users\deleteUser(), Categories\editCategory(), Manufacturers\editManufacturer(), TecTools\editTool(), Users\editUser(), Categories\getAllCategories(), Manufacturers\getAllManufacturers(), TecTools\getAllStatuses(), TecTools\getAllStores(), TecTools\getAllToolsWithFilters(), Categories\getCategoriesForTool(), Categories\getCategory(), CheckIns\getCheckIn(), CheckIns\getCheckInByBarcode(), CheckIns\getCheckInCountForUser(), CheckIns\getCheckInsForMarquee(), Logs\getLogs(), Logs\getLogTypes(), Manufacturers\getManufacturer(), Login\getPasswordReset(), getRequestedPage(), Reservations\getReservationCountForUser(), TecTools\getToolByBarcode(), TecTools\getToolByID(), TecTools\getToolCountWithFilters(), Login\getUserByEmail(), Users\getUserByID(), Categories\isCategoryInUse(), Manufacturers\isManufacturerInUse(), CheckIns\isToolCheckedIn(), Reservations\isToolReserved(), Manufacturers\manufacturerExists(), Categories\removeAllCategoriesFromTool(), Login\resetPassword(), Login\resetPasswordVerify(), RCMSTables\retrieveData(), CheckIns\saveCheckInComment(), Subscriptions\setSubName(), LoginTest\test_SignUp_DuplicateEmail_UserIsNotCreated(), and Reservations\userOwnsReservation().
fixURLQueryQuestionMarks()
static fixURLQueryQuestionMarks () static
Giver mulighed for at skrive "QMARK" i en URL i stedet for et spørgsmålstegn (?)
Nødvendig da RCMSTables erstatter spørgsmålstegn med specifikke værdier, men vi skal også bruge spørgsmålstegn for at betegne URL parametre
Eksempel:
$buttons = array(array("button" => '<input type="button" class="btn rbooking-btn" onclick="location.pathname = `/admin/users/editQMARKuserid=?`" value="Rediger bruger" >', "value" => "id"));
Returns
void
Definition at line 386 of file RCMS.php.
References Helpers\redirect().
getCron()
getCron ()
Returnerer instansen af Cron klassen
Returns
Cron
Definition at line 349 of file RCMS.php.
References $Cron.
Referenced by Cronjobs\deleteOldReservations().
getHomeFolder()
getHomeFolder ()
Returnere stien til hjemme/root mappen
F.eks. "/"
Returns
string
Definition at line 261 of file RCMS.php.
References $homefolder.
Referenced by Helpers\isFrontPage().
getMySQLi()
getMySQLi ()
Returnere den oprettede MySQL forbindelse
Returns
mysqli
Definition at line 279 of file RCMS.php.
References $mysqli.
Referenced by Helpers\isFrontPage().
getRelativeUploadsFolder()
getRelativeUploadsFolder ()
Returnerer den relative sti til uploads mappen, ex. /uploads/tools/images
Returns
string
Definition at line 251 of file RCMS.php.
References $relativeUploadsFolder.
Referenced by TecTools\__construct().
getRequestedPage()
getRequestedPage ()
Henter den side som brugeren gerne vil se fra 'pages' tabellen i databasen
Returns
array|null
Definition at line 327 of file RCMS.php.
References $result, and execute().
Referenced by Template\display_content().
getTemplateFolder()
getTemplateFolder ()
Returnere stien til template mappen
F.eks. "/template/tectools"
Returns
string
Definition at line 271 of file RCMS.php.
References $templatefolder.
Referenced by TecTools\contactCustomerService(), Template\display_content(), Cronjobs\sendMailOldReservationDeleted(), and Login\sendResetPasswordMail().
getUploadsFolder()
getUploadsFolder ()
Returnerer den absolutte sti til uploads mappen, ex. /home2/virtusbc/tectool.virtusb.com/public_html/include/../uploads/tools/images
Returns
string
Definition at line 243 of file RCMS.php.
References $uploadsfolder.
Referenced by TecTools\__construct().
instantiatePlugins()
instantiatePlugins () private
Instantiere alle plugins der ligger i $pluginsToLoad arrayet og tilføjer dem til $GLOBALS arrayet, så den kan bruges alle steder i koden Metoden instantiere IKKE abstrakte klasser
Returns
void
Exceptions
ReflectionException
Definition at line 218 of file RCMS.php.
References newGlobal().
Referenced by __construct().
newGlobal()
newGlobal (string $name, object $obj) private
Opretter en variabel i $GLOBALS arrayet, $GLOBALS er et indbygget array i PHP som er tilgængeligt alle steder i koden
Parameters
string $name Navnet/key på det nye element
object $obj Et objekt/klasse
Returns
void
Definition at line 235 of file RCMS.php.
Referenced by instantiatePlugins().
recursive_require_plugins()
recursive_require_plugins (string $path) private
Loader alle de klasser som ligger i plugins mappen, så instantiatePlugins() metoden kan instantiere dem Loader IKKE klasser hvor shouldAutoLoad er false
Parameters
string $path Stien til plugins mappen
Returns
void
Definition at line 174 of file RCMS.php.
References shouldAutoLoad().
Referenced by __construct().
shouldAutoLoad()
shouldAutoLoad ($file) private
Definition at line 206 of file RCMS.php.
Referenced by recursive_require_plugins().
Field Documentation
$Cron
Cron $Cron = null private
Definition at line 75 of file RCMS.php.
Referenced by getCron().
$database
string $database private
Navnet på databasen
Definition at line 43 of file RCMS.php.
Referenced by __construct().
$Helpers
Helpers $Helpers
Definition at line 54 of file RCMS.php.
$homefolder
string $homefolder private
Root mappen, som regel "/"
Definition at line 91 of file RCMS.php.
Referenced by __construct(), and getHomeFolder().
$host
string $host private
Domæne eller IP til databasen
Definition at line 25 of file RCMS.php.
Referenced by __construct().
$Login
Login $Login
Definition at line 64 of file RCMS.php.
$Logs
Logs $Logs
Definition at line 69 of file RCMS.php.
$Mailer
Mailer $Mailer
Definition at line 85 of file RCMS.php.
$mysqli
mysqli $mysqli private
Forbindelse til databasen
Definition at line 49 of file RCMS.php.
Referenced by getMySQLi().
$pass
string $pass private
Adgangskode til databasen
Definition at line 37 of file RCMS.php.
Referenced by __construct().
$pluginsToLoad
array $pluginsToLoad = [] private
Definition at line 116 of file RCMS.php.
$relativeUploadsFolder
string $relativeUploadsFolder private
Relative sti til uploads mappen
Definition at line 110 of file RCMS.php.
Referenced by getRelativeUploadsFolder().
$StripeWrapper
StripeWrapper $StripeWrapper
Definition at line 80 of file RCMS.php.
$Template
Template $Template
Definition at line 59 of file RCMS.php.
$templatefolder
string $templatefolder private
Template mappen For TecTools er den "/template/tectools"
Definition at line 98 of file RCMS.php.
Referenced by __construct(), and getTemplateFolder().
$uploadsfolder
string $uploadsfolder private
Absolutte sti til uploads mappen
Definition at line 104 of file RCMS.php.
Referenced by __construct(), and getUploadsFolder().
$user
string $user private
Brugernavn til databasen
Definition at line 31 of file RCMS.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
include/RCMS.php