TecTools: Template Class Reference
Template Class Reference
Public Member Functions
__construct (RCMS $RCMS)
display_content ()
display_404 ()
Data Fields
RCMS $RCMS
Detailed Description
Class Template Denne klasse står primært for at vise indhold til brugeren Den tjekker også på om brugeren må se det indhold de anmoder om Andre metoder der omhandler indhold kan tilføjes i denne klasse
Definition at line 11 of file Template.php.
Constructor & Destructor Documentation
__construct()
__construct (RCMS $RCMS)
Definition at line 17 of file Template.php.
References $RCMS.
Member Function Documentation
display_404()
display_404 ()
Hvis en side ikke eksisterer, benyttes denne metode for at give besked til brugeren
Sætter den HTTP status som browseren modtager til 404 Page Not Found
Returns
void
Definition at line 75 of file Template.php.
Referenced by display_content().
display_content()
display_content ()
Loader den side som brugeren gerne vil se, fra databasen, hvis den eksisterer og brugeren har adgang
Adgang har to niveauer
Hvis require_login er sat til true, kan man kun se siden hvis man er logget ind
Hvis is_admin_page er sat til true, kan man kun se siden hvis man er admin
Returns
void|string
Definition at line 31 of file Template.php.
References display_404(), RCMS\getRequestedPage(), and RCMS\getTemplateFolder().
Field Documentation
$RCMS
RCMS $RCMS
Definition at line 15 of file Template.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
include/Template.php