TecTools: RCMSTables Class Reference
RCMSTables Class Reference
Public Member Functions
__construct (RCMS $RCMS)
createRCMSTable (string $id, string $table, array $columns, ?array $settings=array(), ?array $where=array(), ?string $order=null, ?array $buttons=array(), ?array $dropdown=null)
Static Public Member Functions
static isEmpty (array $array)
Data Fields
RCMS $RCMS
array $columns
array $where
array $order
array $buttons
array $dropdown
array $settings
Private Member Functions
createHTML (string $id)
buildRows (string $id, array $rows)
loadAjax ()
countRows (string $table, array $columns, array $where, string $order, array $settings)
retrieveData (string $table, array $columns, array $where, string $order, array $settings)
logQuery (array $settings, string $query, array $whereArr)
Static Private Member Functions
static pluck (array $a, string $prop)
Private Attributes
array $table
Detailed Description
Class RCMSTables Denne klasse bruges til at oprette HTML tabeller på siden. Tabeller oprettet med denne klasse indeholder bl.a. paginering/sideskift, sortering og dropdown indhold.
En anden god ting ved at benytte denne klasse, til at oprette tabeller, er at man slipper næsten helt for at skrive noget SQL, da klassen genererer og eksekverer det meste for en
Definition at line 14 of file RCMSTables.php.
Constructor & Destructor Documentation
__construct()
__construct (RCMS $RCMS)
Definition at line 31 of file RCMSTables.php.
References $RCMS.
Member Function Documentation
buildRows()
buildRows (string $id, array $rows) private
Udskriver HTML tabel rækkerne
Parameters
string $id
array $rows
Returns
void
Definition at line 153 of file RCMSTables.php.
References $buttons, $columns, $dropdown, $order, $pages, $settings, $table, $where, and countRows().
Referenced by createHTML(), and loadAjax().
countRows()
countRows (string $table, array $columns, array $where, string $order, array $settings) private
Returnerer hvor mange rækker data der er i databasen, hvor søgetekst og sidenummer er taget i mente hvis de er sat
Parameters
string $table
array $columns
array $where
string $order
array $settings
Returns
int
Definition at line 297 of file RCMSTables.php.
References $columns, $order, $settings, $where, and retrieveData().
Referenced by buildRows().
createHTML()
createHTML (string $id) private
Denne metode udskriver HTML tabellen
Parameters
string $id
Returns
void
Definition at line 93 of file RCMSTables.php.
References $buttons, $columns, $order, $settings, $table, $where, buildRows(), and retrieveData().
Referenced by createRCMSTable().
createRCMSTable()
createRCMSTable (string $id, string $table, array $columns, ?array $settings = array(), ?array $where = array(), ?string $order = null, ?array $buttons = array(), ?array $dropdown = null)
Denne metode laver data-tabellen og er den eneste metode som man er nød til at kalde manuelt
Den opsætter konfiguration, udskriver HTML og håndterer AJAX
Parameters
string $id
string $table
array $columns
array | null $settings
array | null $where
null | string $order
array | null $buttons
null | array $dropdown
Returns
void
Definition at line 49 of file RCMSTables.php.
References $_GET, $buttons, $columns, $dropdown, $order, $settings, $table, $where, createHTML(), and loadAjax().
isEmpty()
static isEmpty (array $array) static
Tjekker rekursivt om et array er tomt
Parameters
array $array
Returns
bool
Definition at line 533 of file RCMSTables.php.
loadAjax()
loadAjax () private
Loader data og udskriver tabellen som HTML som bruges til AJAX requests
Returns
void
Definition at line 241 of file RCMSTables.php.
References $_GET, $columns, $order, $settings, $table, $where, buildRows(), and retrieveData().
Referenced by createRCMSTable().
logQuery()
logQuery (array $settings, string $query, array $whereArr) private
Kan gemme de queries der bliver kørt i en tekstfil Bruges til at debugge problemer
Parameters
array $settings
string $query
array $whereArr
Returns
void
Definition at line 556 of file RCMSTables.php.
References $settings.
Referenced by retrieveData().
pluck()
static pluck (array $a, string $prop) static private
Kan plukke en bestemt egenskab fra hvert associativ array i et numerisk array
Returnerer et array af egenskabsværdierne fra hvert element
Bruges f.eks. i retrieveData metoden
Reference: linje 515 i https://github.com/DataTables/DataTables/blob/master/examples/server_side/scripts/ssp.class.php
Parameters
array $a Array som der skal plukkes data fra
string $prop Den property/key/egenskab der skal plukkes
Returns
array Array af egenskabsværdierne
Definition at line 583 of file RCMSTables.php.
retrieveData()
retrieveData (string $table, array $columns, array $where, string $order, array $settings) private
Denne metode bygger den komplette SQL query op, der skal køres, på den specifikke tabel i DB med WHERE, ORDER, LIMIT osv. taget i mente
Parameters
string $table
array $columns
array $where
string $order
array $settings
Returns
array
Definition at line 320 of file RCMSTables.php.
References $columns, $order, $result, $settings, $where, RCMS\execute(), and logQuery().
Referenced by countRows(), createHTML(), and loadAjax().
Field Documentation
$buttons
array $buttons
Definition at line 29 of file RCMSTables.php.
Referenced by buildRows(), createHTML(), and createRCMSTable().
$columns
array $columns
Definition at line 29 of file RCMSTables.php.
Referenced by buildRows(), countRows(), createHTML(), createRCMSTable(), loadAjax(), and retrieveData().
$dropdown
array $dropdown
Definition at line 29 of file RCMSTables.php.
Referenced by buildRows(), and createRCMSTable().
$order
array $order
Definition at line 29 of file RCMSTables.php.
Referenced by buildRows(), countRows(), createHTML(), createRCMSTable(), loadAjax(), and retrieveData().
$RCMS
RCMS $RCMS
Definition at line 18 of file RCMSTables.php.
Referenced by __construct().
$settings
array $settings
Definition at line 29 of file RCMSTables.php.
Referenced by buildRows(), countRows(), createHTML(), createRCMSTable(), loadAjax(), logQuery(), and retrieveData().
$table
array $table private
Definition at line 29 of file RCMSTables.php.
Referenced by buildRows(), createHTML(), createRCMSTable(), and loadAjax().
$where
array $where
Definition at line 29 of file RCMSTables.php.
Referenced by buildRows(), countRows(), createHTML(), createRCMSTable(), loadAjax(), and retrieveData().
The documentation for this class was generated from the following file:
include/plugins/RCMSTables/RCMSTables.php