TecTools: LoginTest Class Reference
LoginTest Class Reference
Public Member Functions
test_SignUp_EverythingValid_CreatesUser ()
test_SignUp_DuplicateEmail_UserIsNotCreated ()
Protected Member Functions
setUp ()
tearDown ()
Protected Attributes
RCMS $RCMS
TecTools $TecTools
Static Protected Attributes
static array $userTemplate
Detailed Description
Definition at line 9 of file LoginTest.php.
Member Function Documentation
setUp()
setUp () protected
Definition at line 26 of file LoginTest.php.
References setupTestDatabase().
tearDown()
tearDown () protected
Definition at line 32 of file LoginTest.php.
References RCMS\closeRCMS(), and setupTestDatabase().
test_SignUp_DuplicateEmail_UserIsNotCreated()
test_SignUp_DuplicateEmail_UserIsNotCreated ()
Test at en bruger ikke bliver oprettet, hvis der allerede eksisterer en bruger med den email
Definition at line 60 of file LoginTest.php.
References $user, and RCMS\execute().
test_SignUp_EverythingValid_CreatesUser()
test_SignUp_EverythingValid_CreatesUser ()
Definition at line 41 of file LoginTest.php.
References $user.
Field Documentation
$RCMS
RCMS $RCMS protected
Definition at line 11 of file LoginTest.php.
$TecTools
TecTools $TecTools protected
Definition at line 13 of file LoginTest.php.
$userTemplate
array $userTemplate static protected
Initial value:
= [
      'email' => 'test@user.dk',
      'password' => 'password',
      'firstname' => 'Test',
      'lastname' => 'User',
      'phone' => '11111111',
      'address' => 'Test Road 12',
      'city' => 'TestCity',
      'zipcode' => '2750'
    ]
Definition at line 15 of file LoginTest.php.
The documentation for this class was generated from the following file:
tests/LoginTest.php