TecTools: template/tectools/layout/frontpage.php File Reference
frontpage.php File Reference
Variables
$TecTools = $GLOBALS['TecTools']
$GlobalHandlers = $GLOBALS['GlobalHandlers']
$categories = $TecTools->Categories->getAllCategories()
$tools = $TecTools->getAllToolsWithFilters()
$checkInsMarquee = $TecTools->CheckIns->getCheckInsForMarquee()
$chunks = array_chunk($checkInsMarquee, 3)
foreach($categories as $category)($_GET['categories']) &&in_array($category['CategoryID'] $_GET ['categories'] = isset($_GET['search-text']) ? $_GET['search-text'] : ''
foreach($categories as $category)($_GET['categories']) &&in_array($category['CategoryID'] false
foreach($tools as $tool)($tool['Categories'] as $category) endforeach
else __pad0__
else der matcher dine kriterier</h5 ></div > endif
Variable Documentation
$_GET
foreach ($categories as $category) ($_GET[ 'categories']) &&in_array($category[ 'CategoryID'] $_GET[ 'categories'] = isset($_GET['search-text']) ? $_GET['search-text'] : ''
Definition at line 45 of file frontpage.php.
Referenced by Login\__construct(), RCMSTables\createRCMSTable(), TecTools\displayFrontPagePagination(), TecTools\displayToolCountMessage(), TecTools\getPaginationFilters(), Helpers\isFrontPage(), and RCMSTables\loadAjax().
$categories
$categories = $TecTools->Categories->getAllCategories()
Definition at line 15 of file frontpage.php.
Referenced by TecTools\addTool(), and TecTools\editTool().
$checkInsMarquee
$checkInsMarquee = $TecTools->CheckIns->getCheckInsForMarquee()
Definition at line 17 of file frontpage.php.
$chunks
$chunks = array_chunk($checkInsMarquee, 3)
Definition at line 18 of file frontpage.php.
$GlobalHandlers
GlobalHandlers $GlobalHandlers = $GLOBALS['GlobalHandlers']
Definition at line 13 of file frontpage.php.
$TecTools
$TecTools = $GLOBALS['TecTools']
Definition at line 8 of file frontpage.php.
$tools
$tools = $TecTools->getAllToolsWithFilters()
Definition at line 16 of file frontpage.php.
Referenced by TecTools\getAllTools(), and TecTools\getAllToolsWithFilters().
__pad0__
else __pad0__
Definition at line 110 of file frontpage.php.
endforeach
endforeach
Definition at line 96 of file frontpage.php.
endif
else der matcher dine kriterier</h5></div> endif
Definition at line 116 of file frontpage.php.
false
foreach ($categories as $category) ($_GET[ 'categories']) &&in_array($category[ 'CategoryID'] false
Definition at line 45 of file frontpage.php.