TecTools: template/tectools/layout/my-subscription.php File Reference
my-subscription.php File Reference
Variables
$TecTools = $GLOBALS['TecTools']
$products = $this->RCMS->StripeWrapper->getStripeProducts()
$userProduct = $TecTools->Users->getUserProduct($this->RCMS->Login->getUserID())
foreach($products as $key=> $product)</h2 >< small class="grey-text"> pr md</small ></div >< ul class='collection center'>foreach ($product['metadata'] as $prop) ($product, 200) ? "<strong>
if($userProduct)($userProduct[ 'id']===$product[ 'id'])('Er du helt sikker?') else = $product['name']
else __pad2__
endforeach
Variable Documentation
$products
$products = $this->RCMS->StripeWrapper->getStripeProducts()
Definition at line 15 of file my-subscription.php.
$TecTools
$TecTools = $GLOBALS['TecTools']
Definition at line 12 of file my-subscription.php.
$userProduct
$userProduct = $TecTools->Users->getUserProduct($this->RCMS->Login->getUserID())
Definition at line 17 of file my-subscription.php.
Referenced by Reservations\addReservation(), CheckIns\checkIn(), Users\getUserProduct(), CheckIns\hasUserReachedMaxCheckouts(), and Reservations\hasUserReachedMaxReservations().
($product['metadata'] as $prop)
foreach ($products as $key=> $product)</h2><small class="grey-text"> pr md</small></div><ul class='collection center'>foreach ($product[ 'metadata'] as $prop)($product, 200) ? "<strong>
Initial value:
{$prop['description']}</strong>" : "{$prop['value']} {$prop['description']}" ?>
                                </li>
                            <?php endforeach
Definition at line 40 of file my-subscription.php.
__pad2__
else __pad2__
Definition at line 85 of file my-subscription.php.
else
if($userProduct) ($userProduct['id'] === $product['id']) ('Er du helt sikker?') else = $product['name']
Definition at line 71 of file my-subscription.php.
endforeach
endforeach
Definition at line 106 of file my-subscription.php.