TecTools: template/tectools/layout/pay-fine.php File Reference
pay-fine.php File Reference
Variables
$TecTools = $GLOBALS['TecTools']
if(empty($_GET['hash'])) $paymentHash = $_GET['hash']
$fine = $TecTools->CheckIns->getFineByHash($paymentHash)
Variable Documentation
$fine
$fine = $TecTools->CheckIns->getFineByHash($paymentHash)
Definition at line 20 of file pay-fine.php.
Referenced by CheckIns\getFineByHash(), CheckIns\getFineByID(), CheckIns\payFine(), CheckIns\sendFinePaidEmail(), and CheckIns\sendNewFineEmail().
$paymentHash
if (empty($_GET[ 'hash'])) $paymentHash = $_GET['hash']
Definition at line 19 of file pay-fine.php.
Referenced by CheckIns\payFine().
$TecTools
$TecTools = $GLOBALS['TecTools']
Definition at line 8 of file pay-fine.php.