TecTools: template/tectools/layout/tools/edit.php File Reference
edit.php File Reference
Variables
$TecTools = $GLOBALS['TecTools']
$tool = $TecTools->getToolByID((int) $_GET['toolid'])
$toolCategoryIDs = array_map(static fn($category) => $category['CategoryID'], $tool['Categories'])
$categories = $TecTools->Categories->getAllCategories()
Variable Documentation
$categories
$categories = $TecTools->Categories->getAllCategories()
Definition at line 23 of file edit.php.
$TecTools
$TecTools = $GLOBALS['TecTools']
Definition at line 17 of file edit.php.
$tool
$tool = $TecTools->getToolByID((int) $_GET['toolid'])
Definition at line 19 of file edit.php.
Referenced by CheckIns\checkIn(), CheckIns\checkOut(), TecTools\getAllToolsWithFilters(), CheckIns\getCheckInAjax(), TecTools\getNewestTools(), TecTools\getToolByBarcodeAjax(), TecTools\getToolByID(), CheckIns\sendNewCheckInEmail(), and CheckIns\sendNewFineEmail().
$toolCategoryIDs
$toolCategoryIDs = array_map(static fn($category) => $category['CategoryID'], $tool['Categories'])
Definition at line 21 of file edit.php.