TecTools: template/tectools/layout/users/edit.php File Reference
edit.php File Reference
Variables
$TecTools = $GLOBALS['TecTools']
$userID = (int) $_GET['userid']
if(! $TecTools->Users->authorizeUser($userID)) $user = $TecTools->Users->getUserByID($userID)
Variable Documentation
$TecTools
$TecTools = $GLOBALS['TecTools']
Definition at line 17 of file edit.php.
$user
if (! $TecTools->Users->authorizeUser($userID)) $user = $TecTools->Users->getUserByID($userID)
Definition at line 26 of file edit.php.
Referenced by Users\editUser(), Users\getUserProduct(), Login\log_in(), Login\resetPassword(), CheckIns\sendFinePaidEmail(), CheckIns\sendNewCheckInEmail(), and CheckIns\sendNewFineEmail().
$userID
$userID = (int) $_GET['userid']
Definition at line 19 of file edit.php.
Referenced by CheckIns\addFineToCheckIn(), GlobalHandlers\addLinkToUserFullName(), Reservations\addReservation(), Users\authorizeUser(), CheckIns\checkIn(), Login\createUser(), Reservations\deleteReservation(), Users\editUser(), CheckIns\getCheckInComment(), CheckIns\getCheckInCountForUser(), CheckIns\getCountOfUnpaidFinesForUser(), Reservations\getReservationCountForUser(), Users\getStripeIDForUser(), Users\getUserByID(), CheckIns\hasUserReachedMaxCheckouts(), Reservations\hasUserReachedMaxReservations(), Reservations\isToolReserved(), CheckIns\saveCheckInComment(), and Subscriptions\setSubName().