name: CI

on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "**"

jobs:
  tests:
    runs-on: ubuntu-latest


    steps:
      - name: "Checkout"
        uses: "actions/checkout@v1"

      - name: Install Composer Dependencies
        run: |
          cd include
          composer install --prefer-dist

      - name: Run tests with phpunit
          run: |
            cd include/vendor/bin
            phpunit --testdox tests


#      - name: "Run tests with phpunit"
#        working-directory: "/home/runner/work/tectools/"
#        run: "include/vendor/bin/phpunit --testdox tests"